import pandas as pd
import numpy as np
import torch
from torch.utils.data import TensorDataset, DataLoader
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
import os
from flowMatching.transforms import LogLinearTransform, PiecewiseExponentialTransform, DequantizationTransform
from flowMatching.postprocess import PRECISION_MAP

FEATURES_FULL = [
    'pH(CaCl2)', 'pH(H2O)', 'EC', 'OC', 'CaCO3', 'P', 'N', 'K', 'Elevation'
]

FEATURES_SUBSET = [
    'Clay', 'Sand', 'Silt'
] + FEATURES_FULL

LOG_LINEAR_FEATURES = ['EC', 'OC', 'CaCO3', 'P', 'N', 'K', 'Elevation']
EXP_TAIL_FEATURES = ['pH(CaCl2)', 'pH(H2O)']
SHIFT_LOG_FEATURES = {'Elevation': 200} 

def get_traditional_features(mode):
    if mode in ['chem_phys_nospectral', 'chem_phys_spectral']:
        return FEATURES_SUBSET
    elif mode in ['chem_nospectral', 'chem_spectral']:
        return FEATURES_FULL
    else:
        raise ValueError("Mode must be one of: 'chem_nospectral', 'chem_spectral', 'chem_phys_nospectral', 'chem_phys_spectral'")

def split_and_scale_data(df_full, traditional_features, raw_spectral_features, seed=42):
    # Extract clustering labels for stratification (if present), otherwise use dummy zeros
    # This maintains data split reproducibility and lays groundwork for future conditional clustering models.
    if 'cluster' in df_full.columns:
        y_raw = df_full['cluster'].values
    else:
        y_raw = np.zeros(len(df_full))
        
    class_counts = pd.Series(y_raw).value_counts()
    stratify = y_raw if not (class_counts < 3).any() else None

    df_trainval, df_test, y_trainval, y_test = train_test_split(
        df_full, y_raw, test_size=0.15, random_state=seed, stratify=stratify
    )
    
    stratify_val = y_trainval if stratify is not None else None
    df_train, df_val, y_train, y_val = train_test_split(
        df_trainval, y_trainval, test_size=(0.15/0.85), random_state=seed, stratify=stratify_val
    )

    X_train = df_train[traditional_features].copy()
    X_val = df_val[traditional_features].copy()
    X_test = df_test[traditional_features].copy()

    standard_scaler = StandardScaler()
    standard_scaler.fit(X_train)

    pca_feature_names = []
    spectral_pca_fitted = None
    spectral_scaler_fitted = None

    if len(raw_spectral_features) > 0:
        spectral_scaler_fitted = StandardScaler()
        train_spec_scaled = spectral_scaler_fitted.fit_transform(df_train[raw_spectral_features])
        val_spec_scaled = spectral_scaler_fitted.transform(df_val[raw_spectral_features])
        test_spec_scaled = spectral_scaler_fitted.transform(df_test[raw_spectral_features])

        spectral_pca_fitted = PCA(n_components=0.999)
        train_spec_pca = spectral_pca_fitted.fit_transform(train_spec_scaled)
        val_spec_pca = spectral_pca_fitted.transform(val_spec_scaled)
        test_spec_pca = spectral_pca_fitted.transform(test_spec_scaled)

        n_components = train_spec_pca.shape[1]
        pca_feature_names = [f"Spectral_PC{k+1}" for k in range(n_components)]

        for k, col in enumerate(pca_feature_names):
            X_train[col] = train_spec_pca[:, k]
            X_val[col] = val_spec_pca[:, k]
            X_test[col] = test_spec_pca[:, k]

    all_features = traditional_features + pca_feature_names
    return X_train, X_val, X_test, all_features, standard_scaler, spectral_pca_fitted, spectral_scaler_fitted

def prepare_data(batch_size=64, df_train=None, df_val=None, df_test=None, all_features_ext=None):
    """
    Applies non-linear deep learning data transforms, standardizes variables, and returns DataLoaders.
    It expects pre-split and pre-PCA'd dataframes generated by validation logic or split_and_scale_data.
    """
    X_train_df = df_train.copy()
    X_val_df = df_val.copy()
    X_test_df = df_test.copy()
    all_features = all_features_ext

    print("Applying Transforms...")

    dequant_transform = DequantizationTransform(precision_map=PRECISION_MAP, margin=0.45)
    dequant_transform.fit(X_train_df, X_train_df.columns)

    X_train_df = dequant_transform.transform(X_train_df)

    pe_transform = PiecewiseExponentialTransform(lower_q=0.1, upper_q=0.9)
    pe_transform.fit(X_train_df, EXP_TAIL_FEATURES)

    X_train_df = pe_transform.transform(X_train_df)
    X_val_df = pe_transform.transform(X_val_df)
    X_test_df = pe_transform.transform(X_test_df)

    base_ll_features = [f for f in LOG_LINEAR_FEATURES if f in X_train_df.columns]

    ll_transform = LogLinearTransform(percentile=95, offsets=SHIFT_LOG_FEATURES)
    ll_transform.fit(X_train_df, base_ll_features)

    X_train_df = ll_transform.transform(X_train_df)
    X_val_df = ll_transform.transform(X_val_df)
    X_test_df = ll_transform.transform(X_test_df)

    X_train_df = X_train_df[all_features]
    X_val_df = X_val_df[all_features]
    X_test_df = X_test_df[all_features]

    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train_df.values)
    X_val_scaled = scaler.transform(X_val_df.values)
    X_test_scaled = scaler.transform(X_test_df.values)

    X_train_tensor = torch.tensor(X_train_scaled, dtype=torch.float32)
    X_val_tensor = torch.tensor(X_val_scaled, dtype=torch.float32)
    X_test_tensor = torch.tensor(X_test_scaled, dtype=torch.float32)

    train_dataset = TensorDataset(X_train_tensor)
    val_dataset = TensorDataset(X_val_tensor)
    test_dataset = TensorDataset(X_test_tensor)

    train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
    val_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False)
    test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False)

    transforms = {
        'loglinear': ll_transform,
        'piecewise_exp': pe_transform,
        'dequantization': dequant_transform
    }
    return train_loader, val_loader, test_loader, scaler, all_features, transforms
